### PR TITLE
Feat/init new game data

### PR DESCRIPTION
**Pull request by dongkiat**
## Description

Add functions to generate and initialize the necessary data for a new game

## Changes

**Features**:

- Add function to generate board metadata. Dictionary of metadata necessary for game utilization will be created dynamically based on pre determined variables and returned.
- Add function to generate initial buildings.  Dictionary of initial buildings will be created based on the building pool set and the city size from user input, and then returned.
- Add function to generate new board. Nested array board will be created dynamically based on the city size from user input and returned.

**Refactors**:

- Remove unnecessary comments at the top of file
- Reorder code such that the code created and refactored for requirement change are at the bottom

## Screenshots

image

### CODE REVIEW

**Comment by iamgruuten** [comment]
NRTG, please fix conflict

**Review by iamgruuten — COMMENTED** [review]
should we get get flake8 to work first? otherwise I cant get the code coverage

**Comment by dongkiat** [comment]
@iamgruuten fixed

**Review by DannyOnCode — APPROVED** [review]
lgtm

**Review by iamgruuten — APPROVED** [review]
lgtm

**Pull request merged**
